#!/usr/bin/env python3

import argparse

#
#  stuf I want to add:
#   -l list all game folders
#   -r remove game (appinfo + content)
#   basic checks (access permissions)
#


if __name__ == "__main__":
    print('hello, friend')